plugins {
	id 'java'
	id 'jacoco'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ms-usuario.plazoleta'
version = '0.0.1-SNAPSHOT'
description = 'practica de ms-usuario'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	// JPA: permite mapear clases Java a tablas de base de datos
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// Driver de PostgreSQL: el conector específico para hablar con Postgres
	runtimeOnly 'org.postgresql:postgresql'
	// Validation: anotaciones para validar datos de entrada (@NotBlank, @Email, @Size, etc.)
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// JWT: generar y validar tokens de autenticación
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
}

def jacocoExclusions = [
	'**/MsUsuarioApplication*',
	'**/domain/model/**',
	'**/domain/ports/**',
	'**/domain/exception/**',
	'**/domain/constants/**',
	'**/infrastructure/config/BeanConfiguration*',
	'**/infrastructure/config/SecurityConfig*',
	'**/infrastructure/input/rest/dto/**',
	'**/infrastructure/input/rest/mapper/**',
	'**/infrastructure/input/rest/*RestController*',
	'**/infrastructure/output/persistence/entity/**',
	'**/infrastructure/output/persistence/mapper/**',
	'**/infrastructure/output/persistence/repository/**',
	'**/infrastructure/output/persistence/adapter/**',
]

jacoco {
	toolVersion = "0.8.12"
}

tasks.named('test') {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, excludes: jacocoExclusions)
		}))
	}
	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, excludes: jacocoExclusions)
		}))
	}
	violationRules {
		rule {
			limit {
				minimum = 0.96
			}
		}
	}
}

tasks.named('check') {
	dependsOn jacocoTestCoverageVerification
}
