plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ms-usuario.plazoleta'
version = '0.0.1-SNAPSHOT'
description = 'practica de ms-usuario'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	// JPA: permite mapear clases Java a tablas de base de datos
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// Driver de PostgreSQL: el conector específico para hablar con Postgres
	runtimeOnly 'org.postgresql:postgresql'
	// Validation: anotaciones para validar datos de entrada (@NotBlank, @Email, @Size, etc.)
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
